export const EMISSION_FACTOR_LIGHTS_HOURLY = 0.04;
export const EMISSION_FACTOR_WATER_HEATER_HOURLY = 2.2;
export const EMISSION_FACTOR_WASHING_MACHINE_CYCLE = 0.65;
export const EMISSION_FACTOR_REFRIGERATOR_DAILY = 1.8;
export const EMISSION_FACTOR_AC_HOURLY = 1.2;

export const HIGH_EMISSION_PERCENTAGE_THRESHOLD_TRANSPORT = 30;
export const HIGH_EMISSION_PERCENTAGE_THRESHOLD_FOOD = 25;
export const HIGH_EMISSION_PERCENTAGE_THRESHOLD_ENERGY = 35;
export const HIGH_EMISSION_PERCENTAGE_THRESHOLD_SHOPPING = 20;
export const HIGH_EMISSION_PERCENTAGE_THRESHOLD_WASTE = 15;
