export const REWARD_POINTS_DAILY_MISSION = 250;
export const REWARD_XP_DAILY_MISSION = 50;

export const REWARD_POINTS_COMMUNITY_POST = 50;
export const REWARD_XP_COMMUNITY_POST = 25;

export const REWARD_POINTS_GOAL_COMPLETE = 300;
export const REWARD_XP_GOAL_COMPLETE = 150;

export const REWARD_POINTS_SCAN = 150;
export const REWARD_XP_SCAN = 50;

export const REWARD_POINTS_ARTICLE_READ_MULTIPLIER = 2;
